### ISSUE TITLE
module namespace 需要自定义

### ISSUE THREAD

**Issue by myxiaoao** [packagit/packagit#1]
现在默认的都是 Packagit 前缀。

**Comment by myxiaoao** [comment]
https://github.com/packagit/packagit/blob/a30f52c4123290d32ece8d5a95f521bbae648016/src/Commands/MakeCommand.php#L73

在项目 config 文件创建 modules.php ，这里应该是 array_merge 反了。

**Comment by zencodex** [comment]
support by v1.0.3
