### ISSUE TITLE
执行流程应该调整下吧

### ISSUE THREAD

**Issue by myxiaoao** [packagit/packagit#3]
1.  `p custom` 生成自定义配置文件
2.  `p new` 生成模块

同时 custom 的时候，应该就可以安装 `wikimedia/composer-merge-plugin` 同时配置 composer ；
app.php 的 providers 在模块中，已经声明了，这里应该不需要再配置了吧。

@zencodex

**Comment by zencodex** [comment]
顺序我调整下，`p custom` 为可选，也并非必须，需要自己定义 namespace 时才需要。

后面 composer 的配置 和 provider 配置都是需要的。
