### ISSUE TITLE
服务提供者是否可以自动加载呢？

### ISSUE THREAD

**Issue by mouyong** [packagit/packagit#9]
开发完成了项目后，一般期望能使用 `composer.json` 的 `extra` 配置，完成服务提供者的自动加载，并且期望能通过事件、数据的的方式完成插件的各方面管理。不希望改动到文件 `app/config.php` 与主项目的各项文件内容。

这里之前的参考资料：

注册模块的命名空间：https://gitee.com/fresns/plugin-manager/blob/master/src/Providers/PluginServiceProvider.php#L35-38

注册每一个插件的命名空间、别名：https://gitee.com/fresns/plugin-manager/blob/master/src/Support/Plugin.php#L118-120

**Comment by zencodex** [comment]
感谢建议，还不太清楚你描述的需求是什么，如果是想自动注册provider，那`p new moduleName`的时候就可以做到。现在手动在 config/app.php 加入，可以自由控制一下。有的module 可能未完成，并不想正式产生作用，那就可以不加配置，但可以保留开发代码。

或者你可以贡献下 PR，看看能完成哪部分能力

**Comment by mouyong** [comment]
@zencodex 我想表达的是，app.php 是 laravel 项目级别的配置。希望不改动 laravel 框架的东西，自动完成模块的注册。

将 `主项目`，`插件启用停用管理`, `插件开发管理` 的功能解耦化。以达到插件在不同项目间的通用。

**Comment by mouyong** [comment]
因为自己的代码感觉写的不好，所以没用贡献代码，只提到了这个想法。

**Comment by zencodex** [comment]
谢谢建议，暂时还没太好的想法，以后可以遇到具体问题，具体解决。
